### ISSUE TITLE
[TODO-IF-POSSIBLE] Reduce file size when retain simplicity

### ISSUE THREAD

**Issue by eebssk1** [eebssk1/SRBeep2#1]
This module is currently compiled with MingW, which is why it's so bloated.
The compiler retains and exports all the functions when linking against static libraries which are not actually needed.

Find a way to solve this while retain simplicity.

**Comment by CRBRC217** [comment]
A big thank you for keeping the tool alive. Just tried your updated release SRBeep2-win64. The download package does not contain the bin folder with SDL2.dll. So, used the one from earlier release. This time however, when you activate the record function via a hotkey or the UI, the entire OBS client hangs before crashing. It's the same behaviour upon deleting SDL2.dll.

The logs howver say SRBeep2 is loaded.

`22:08:57.223: video settings reset:
22:08:57.223: 	base resolution:   1366x768
22:08:57.223: 	output resolution: 1024x576
22:08:57.223: 	downscale filter:  Bicubic
22:08:57.223: 	fps:               30/1
22:08:57.223: 	format:            NV12
22:08:57.223: 	YUV mode:          Rec. 709/Partial
22:08:57.318: NV12 texture support not available
22:08:57.318: P010 texture support not available
22:08:57.319: Audio monitoring device:
22:08:57.319: 	name: Default
22:08:57.319: 	id: default
22:08:57.396: ---------------------------------
22:08:59.550: No AJA devices found, skipping loading AJA UI plugin
22:08:59.550: Failed to initialize module 'aja-output-ui.dll'
22:09:03.275: No AJA devices found, skipping loading AJA plugin
22:09:03.275: Failed to initialize module 'aja.dll'
22:09:03.416: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
22:09:03.590: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
22:09:03.895: Failed to load 'en-US' text for module: 'decklink-captions.dll'
22:09:04.506: Failed to load 'en-US' text for module: 'decklink-output-ui.dll'
22:09:05.019: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
22:09:05.019: Failed to initialize module 'decklink.dll'
22:09:06.905: [AMF] Unable to load 'amfrt64.dll', error code 126.
22:09:06.911: [AMF] AMF Test failed due to one or more errors.
22:09:06.911: Failed to initialize module 'enc-amf.dll'
22:09:10.949: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
22:09:11.044: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
22:09:11.445: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
22:09:25.740: [obs-browser]: Version 2.21.1
22:09:25.740: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2591+g4204d54+chromium-103.0.5060.134 (compiled)
22:09:38.718: [noise suppress]: NVIDIA denoiser disabled, redistributable not found or could not be loaded.
22:09:38.722: Failed to get NVVideoEffects.dll version info size
22:09:38.731: [NVIDIA VIDEO FX]: FX disabled, redistributable not found or could not be loaded.
22:09:45.897: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.2.2 | RPC Version: 1)
22:09:45.897: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.4.3 | Qt version (run-time): 6.4.3
22:09:45.897: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
22:09:47.135: [obs-websocket] [obs_module_load] Module loaded.
22:09:51.123: [vlc-video]: VLC 3.0.18 Vetinari found, VLC video source enabled
22:09:54.097: ---------------------------------
22:09:54.097:   Loaded Modules:
22:09:54.097:     win-wasapi.dll
22:09:54.097:     win-dshow.dll
22:09:54.097:     win-capture.dll
22:09:54.097:     vlc-video.dll
22:09:54.097:     text-freetype2.dll
22:09:54.097:     SRBeep2.dll
22:09:54.097:     rtmp-services.dll
22:09:54.097:     obs-x264.dll
22:09:54.097:     obs-websocket.dll
22:09:54.097:     obs-vst.dll
22:09:54.097:     obs-transitions.dll
22:09:54.097:     obs-text.dll
22:09:54.097:     obs-qsv11.dll
22:09:54.097:     obs-outputs.dll
22:09:54.097:     obs-filters.dll
22:09:54.097:     obs-ffmpeg.dll
22:09:54.098:     obs-browser.dll
22:09:54.098:     image-source.dll
22:09:54.098:     frontend-tools.dll
22:09:54.098:     decklink-output-ui.dll
22:09:54.098:     decklink-captions.dll
22:09:54.098:     coreaudio-encoder.dll
22:09:54.098: ---------------------------------
22:09:54.195: ==== Startup complete ===============================================
22:09:56.085: All scene data cleared
22:09:56.085: ------------------------------------------------
22:09:56.650: [win-wasapi: 'Desktop Audio'] update settings:
22:09:56.650: 	device id: default
22:09:56.650: 	use device timing: 1
22:09:56.652: [Loaded global audio device]: 'Desktop Audio'
22:09:56.653: [win-wasapi: 'Mic/Aux'] update settings:
22:09:56.653: 	device id: default
22:09:56.653: 	use device timing: 0
22:09:56.666: [Loaded global audio device]: 'Mic/Aux'
22:09:56.836: [WASAPISource::TryInitialize]:[Microphone / Line In (IDT High Definition Audio CODEC)] Failed to initialize audio client: 80070005
22:09:56.836: WASAPI: Device 'default' failed to start (source: Mic/Aux)
22:09:56.862: [duplicator-monitor-capture: 'Display Capture'] update settings:
22:09:56.862: 	display:  (1366x768)
22:09:56.862: 	cursor: true
22:09:56.862: 	method: DXGI
22:09:56.862: 	id: \\?\DISPLAY#LGD0266#4&19079f18&2&UID67568640#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
22:09:56.862: 	alt_id: \\.\DISPLAY1
22:09:56.862: 	setting_id: \\?\DISPLAY#LGD0266#4&19079f18&2&UID67568640#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
22:09:56.862: 	force SDR: false
22:09:57.054: Switched to scene 'Scene'
22:09:57.062: WASAPI: Device 'Speakers / Headphones (IDT High Definition Audio CODEC)' [48000 Hz] initialized
22:09:57.343: adding 192 milliseconds of audio buffering, total audio buffering is now 192 milliseconds (source: Desktop Audio)
22:09:57.343: 
22:09:57.408: ------------------------------------------------
22:09:57.408: Loaded scenes:
22:09:57.408: - scene 'Scene':
22:09:57.412:     - source: 'Display Capture' (monitor_capture)
22:09:57.413: ------------------------------------------------
22:10:24.312: Starting recording due to hotkey
22:10:24.352: ---------------------------------
22:10:24.352: [x264 encoder: 'advanced_video_recording'] preset: ultrafast
22:10:24.378: [x264 encoder: 'advanced_video_recording'] settings:
22:10:24.378: 	rate_control: ABR
22:10:24.378: 	bitrate:      1000
22:10:24.378: 	buffer size:  1000
22:10:24.378: 	crf:          23
22:10:24.378: 	fps_num:      30
22:10:24.378: 	fps_den:      1
22:10:24.378: 	width:        1024
22:10:24.378: 	height:       576
22:10:24.378: 	keyint:       250
22:10:24.378: 
22:10:24.495: ---------------------------------
22:10:24.535: [FFmpeg aac encoder: 'Track1'] bitrate: 160, channels: 2, channel_layout: stereo
22:10:24.535: `

**Comment by eebssk1** [comment]
Looks impossible without rebuild all the dependencies.

**Comment by eebssk1** [comment]
Or maybe I can compress it with UPX...
